baseURL = "https://pranet.cse.iith.ac.in/"
title = "Practical Networking & Blockchain Lab"
author = "username"
locale = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
showNews = true
mainSections = ['News']
googleFonts = true

  [params.logo]
  main = "images/logo.svg"
  alt = "Pranet"
  size = "h-8 w-auto md:h-10"

  [params.site]
  name = "PRANET"

  [params.icon]
  # If you want to use FontAwesome, set this parameter to true.
  fontawesome = true

  # You can also use Bootstrap Icons.
  bootstrap = true

  [params.homepage_meta_tags]
  meta_description = "Network and Blockchain research lab at IITH"
  meta_og_title = "PraNet"
  meta_og_type = "website"
  


[menu]
  [[menu.main]]
  identifier = "people"
    name = "People"
  url = "/people/"
  weight = 3

  [[menu.main]]
  identifier = "pubs"
  name = "Publications"
  url = "/publications/"
  weight = 4

  [[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

  # Footer Menu
  [[menu.footer]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.footer]]
  name = "CSE Dept"
  url = "https://cse.iith.ac.in"
  #pre = "<i class='bi bi-github text-2xl'></i>"
  weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
    unsafe = true

